export const FORM_STEPS = {
	BASIC_INFO: 1,
	COOKING_EXPERIENCE: 2,
	FAVORITE_CUISINES: 3,
	SERVINGS: 4,
	DIETARY_INFO: 5,
	COOKING_TIME: 6,
	BUDGET: 7,
	SHOPPING_FREQUENCY: 8,
	TOTAL: 8,
	FORM_PROGRESS_KEY: 'FormProgress',
} as const;

export type FormStep = typeof FORM_STEPS[keyof typeof FORM_STEPS];
