import { defineNuxtPlugin } from 'nuxt/app';
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import {
	faUser,
	faUtensils,
	faClock,
	faCoins,
	faWallet,
	faSackDollar,
	faMoneyBillWave,
	faMoneyBills,
	faVault,
	faCircleExclamation,
	faFireFlameCurved,
	faCartShopping,
	faWeightScale,
	faBalanceScale,
	faPersonRunning,
	faDumbbell,
	faFire,
	faUserGear,
	faCalculator,
	faClipboardCheck,
	faUsers,
	faBars,
	faListCheck,
	faGear,
	faRotate,
	faChevronLeft,
	faChevronRight,
	faCalendarCheck,
	faHome,
	faCalendarDays,
	faBook,
} from '@fortawesome/free-solid-svg-icons';

library.add(
	faUser,
	faUtensils,
	faClock,
	faCoins,
	faWallet,
	faSackDollar,
	faMoneyBillWave,
	faMoneyBills,
	faVault,
	faCircleExclamation,
	faFireFlameCurved,
	faCartShopping,
	faWeightScale,
	faBalanceScale,
	faPersonRunning,
	faDumbbell,
	faFire,
	faUserGear,
	faCalculator,
	faClipboardCheck,
	faUsers,
	faBars,
	faListCheck,
	faGear,
	faRotate,
	faChevronLeft,
	faChevronRight,
	faCalendarCheck,
	faHome,
	faCalendarDays,
	faBook,
);

export default defineNuxtPlugin((app) => {
	app.vueApp.component('FontAwesomeIcon', FontAwesomeIcon);
});
